"""shared users col

Revision ID: 2ce19febde50
Revises: e5d31f2e90a2
Create Date: 2025-01-26 18:14:15.260024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce19febde50'
down_revision: Union[str, None] = 'e5d31f2e90a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_shared_directories', sa.Column('sharedWithId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_shared_directories', 'user', ['sharedWithId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_shared_directories', type_='foreignkey')
    op.drop_column('note_shared_directories', 'sharedWithId')
    # ### end Alembic commands ###
