"""user request table

Revision ID: 5c226426e9eb
Revises: 7345939b1d3b
Create Date: 2024-08-14 18:43:04.404891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c226426e9eb'
down_revision: Union[str, None] = '7345939b1d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_request')
    # ### end Alembic commands ###
