"""subclass to character

Revision ID: 7345939b1d3b
Revises: 93cdf85ea186
Create Date: 2024-08-05 18:32:39.765663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7345939b1d3b'
down_revision: Union[str, None] = '93cdf85ea186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('subclassId', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'character', ['subclassId'])
    op.create_foreign_key(None, 'character', 'subclass', ['subclassId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_column('character', 'subclassId')
    # ### end Alembic commands ###
