"""tags and notes colors

Revision ID: e5d31f2e90a2
Revises: cd080a3b3eff
Create Date: 2025-01-25 15:19:58.651556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d31f2e90a2'
down_revision: Union[str, None] = 'cd080a3b3eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('userId', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('value', sa.String(), nullable=True),
        sa.Column('toggle', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tag', sa.Column('color', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('tag_shared_users', sa.Column('sharedWithId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag_shared_users', 'user', ['sharedWithId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_shared_users', type_='foreignkey')
    op.drop_column('tag_shared_users', 'sharedWithId')
    op.drop_column('tag', 'icon')
    op.drop_column('tag', 'color')
    op.drop_table('user_setting')
    # ### end Alembic commands ###
