"""ClassTable model added

Revision ID: 0995a686bed0
Revises: dbb78926edf0
Create Date: 2024-05-12 18:33:17.312391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0995a686bed0'
down_revision: Union[str, None] = 'dbb78926edf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.Column('profBonus', sa.String(), nullable=True),
    sa.Column('cantripsKnown', sa.String(), nullable=True),
    sa.Column('spellsKnown', sa.String(), nullable=True),
    sa.Column('level1SpellSlots', sa.String(), nullable=True),
    sa.Column('level2SpellSlots', sa.String(), nullable=True),
    sa.Column('level3SpellSlots', sa.String(), nullable=True),
    sa.Column('level4SpellSlots', sa.String(), nullable=True),
    sa.Column('level5SpellSlots', sa.String(), nullable=True),
    sa.Column('level6SpellSlots', sa.String(), nullable=True),
    sa.Column('level7SpellSlots', sa.String(), nullable=True),
    sa.Column('level8SpellSlots', sa.String(), nullable=True),
    sa.Column('level9SpellSlots', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('statsheet_characterId_key', 'statsheet', type_='unique')
    op.drop_constraint('statsheet_characterId_fkey', 'statsheet', type_='foreignkey')
    op.drop_column('statsheet', 'characterId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statsheet', sa.Column('characterId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('statsheet_characterId_fkey', 'statsheet', 'character', ['characterId'], ['id'])
    op.create_unique_constraint('statsheet_characterId_key', 'statsheet', ['characterId'])
    op.drop_table('class_table')
    # ### end Alembic commands ###
