"""Spells updated

Revision ID: 0bb0e2791b5d
Revises: 5cb9d00e8076
Create Date: 2024-05-13 13:18:28.744995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb0e2791b5d'
down_revision: Union[str, None] = '5cb9d00e8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'spellcomponents', 'spells', ['spellId'], ['id'])
    op.add_column('spells', sa.Column('concentration', sa.Boolean(), nullable=True))
    op.add_column('spells', sa.Column('range', sa.String(), nullable=True))
    op.drop_column('spells', 'spellComponentId')
    op.drop_column('spells', 'type')
    op.drop_constraint('subclass_classId_fkey', 'subclass', type_='foreignkey')
    op.drop_column('subclass', 'classId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subclass', sa.Column('classId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subclass_classId_fkey', 'subclass', 'class', ['classId'], ['id'])
    op.add_column('spells', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('spells', sa.Column('spellComponentId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('spells', 'range')
    op.drop_column('spells', 'concentration')
    op.drop_constraint(None, 'spellcomponents', type_='foreignkey')
    # ### end Alembic commands ###
