"""added note tags and directories

Revision ID: 22f4be29ef5b
Revises: 1b1afa442df3
Create Date: 2024-12-31 16:14:14.529174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f4be29ef5b'
down_revision: Union[str, None] = '1b1afa442df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('directory', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    
    op.create_table(
        'tag',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String()),
        sa.Column('description', sa.Text()),
        sa.Column('created', sa.DateTime()),
        sa.Column('updated', sa.DateTime()),
        sa.Column('active', sa.Boolean()),
        sa.Column('userId', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table(
        'note_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('noteId', sa.String()),
        sa.Column('tagId', sa.Text()),
        sa.ForeignKeyConstraint(['noteId'], ['note.id'], ),
        sa.ForeignKeyConstraint(['tagId'], ['tag.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table(
        'tag_shared_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tagId', sa.Integer(), nullable=False),
        sa.Column('userId', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tagId'], ['tag.id'], ),
        sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'directory')
    # ### end Alembic commands ###
    
    op.drop_table('tag_shared_users')
    op.drop_table('note_tags')
    op.drop_table('tag')
