"""added userID to user request

Revision ID: 355f0c78d261
Revises: 5c226426e9eb
Create Date: 2024-08-14 19:42:38.516003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355f0c78d261'
down_revision: Union[str, None] = '5c226426e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_request', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_request', type_='foreignkey')
    op.drop_column('user_request', 'userId')
    # ### end Alembic commands ###
