"""Notes can be campaign global

Revision ID: 400bd94224fd
Revises: c646da470fb7
Create Date: 2024-12-26 08:36:16.143030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400bd94224fd'
down_revision: Union[str, None] = 'c646da470fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('campaignId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'campaign', ['campaignId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'campaignId')
    # ### end Alembic commands ###
