"""character and statsheet

Revision ID: 414072279e34
Revises: a709a4ecd53d
Create Date: 2024-01-25 02:42:04.495409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414072279e34'
down_revision: Union[str, None] = 'a709a4ecd53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('languages', sa.String(), nullable=True))
    op.drop_constraint('character_basestatsheetid_key', 'character', type_='unique')
    op.drop_column('character', 'basestatsheetid')
    op.add_column('class', sa.Column('spellCastingAbility', sa.String(), nullable=True))
    op.add_column('statsheet', sa.Column('inspiration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statsheet', 'inspiration')
    op.drop_column('class', 'spellCastingAbility')
    op.add_column('character', sa.Column('basestatsheetid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('character_basestatsheetid_key', 'character', ['basestatsheetid'])
    op.drop_column('character', 'languages')
    op.drop_column('character', 'speed')
    # ### end Alembic commands ###
