"""ext table

Revision ID: 9cbc35a17a0f
Revises: 43a571f53c03
Create Date: 2023-12-30 20:28:07.137402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbc35a17a0f'
down_revision: Union[str, None] = '43a571f53c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_subclasses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.Column('subclassId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['class.id'], ),
    sa.ForeignKeyConstraint(['subclassId'], ['subclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('character', sa.Column('statsheetid', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('basestatsheetid', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('campaignCompatability', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'character', ['basestatsheetid'])
    op.create_unique_constraint(None, 'character', ['statsheetid'])
    op.create_foreign_key(None, 'character', 'statsheet', ['statsheetid'], ['id'])
    op.create_foreign_key(None, 'character', 'statsheet', ['basestatsheetid'], ['id'])
    op.drop_column('character', 'classId')
    op.drop_column('character', 'subclassId')
    op.add_column('inventory', sa.Column('characterId', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'inventory', ['characterId'])
    op.create_foreign_key(None, 'inventory', 'character', ['characterId'], ['id'])
    op.add_column('statsheet', sa.Column('clazzId', sa.Integer(), nullable=True))
    op.add_column('statsheet', sa.Column('subclassId', sa.Integer(), nullable=True))
    op.add_column('statsheet', sa.Column('exp', sa.Integer(), nullable=True))
    op.add_column('statsheet', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('statsheet', sa.Column('type', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'statsheet', ['subclassId'])
    op.create_unique_constraint(None, 'statsheet', ['clazzId'])
    op.create_foreign_key(None, 'statsheet', 'class', ['clazzId'], ['id'])
    op.create_foreign_key(None, 'statsheet', 'subclass', ['subclassId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statsheet', type_='foreignkey')
    op.drop_constraint(None, 'statsheet', type_='foreignkey')
    op.drop_constraint(None, 'statsheet', type_='unique')
    op.drop_constraint(None, 'statsheet', type_='unique')
    op.drop_column('statsheet', 'type')
    op.drop_column('statsheet', 'level')
    op.drop_column('statsheet', 'exp')
    op.drop_column('statsheet', 'subclassId')
    op.drop_column('statsheet', 'clazzId')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'characterId')
    op.add_column('character', sa.Column('subclassId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('classId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_column('character', 'campaignCompatability')
    op.drop_column('character', 'basestatsheetid')
    op.drop_column('character', 'statsheetid')
    op.drop_table('class_subclasses')
    op.drop_table('ext_content')
    op.drop_table('campaign')
    # ### end Alembic commands ###
