"""Added race columns

Revision ID: a60b0f522758
Revises: c81d1ea58fd2
Create Date: 2024-01-15 06:37:23.889703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60b0f522758'
down_revision: Union[str, None] = 'c81d1ea58fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('size', sa.String(), nullable=True))
    op.add_column('race', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('race', sa.Column('alignment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'alignment')
    op.drop_column('race', 'languages')
    op.drop_column('race', 'size')
    # ### end Alembic commands ###
