"""characterID

Revision ID: a709a4ecd53d
Revises: dbb78926edf0
Create Date: 2024-01-25 00:48:30.750285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a709a4ecd53d'
down_revision: Union[str, None] = 'dbb78926edf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('characterId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'race', 'character', ['characterId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column('race', 'characterId')
    # ### end Alembic commands ###
