"""campaign, notes, and classes changed

Revision ID: dd9d9a67175a
Revises: 355f0c78d261
Create Date: 2024-12-26 07:39:13.011035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd9d9a67175a'
down_revision: Union[str, None] = '355f0c78d261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ext_content', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('ext_content', sa.Column('characterId', sa.Integer(), nullable=True))
    op.add_column('ext_content', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('ext_content', sa.Column('previousValue', sa.Integer(), nullable=True))
    op.add_column('ext_content', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('ext_content', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('ext_content', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ext_content', 'updated')
    op.drop_column('ext_content', 'created')
    op.drop_column('ext_content', 'active')
    op.drop_column('ext_content', 'previousValue')
    op.drop_column('ext_content', 'value')
    op.drop_column('ext_content', 'characterId')
    op.drop_column('ext_content', 'userId')
    # ### end Alembic commands ###
