"""Removed statsheet from classes

Revision ID: f656e8870684
Revises: a60b0f522758
Create Date: 2024-01-15 08:50:21.355492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f656e8870684'
down_revision: Union[str, None] = 'a60b0f522758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'class_subclasses', 'subclass', ['subclassId'], ['id'])
    op.drop_constraint('statsheet_clazzId_key', 'statsheet', type_='unique')
    op.drop_constraint('statsheet_subclassId_key', 'statsheet', type_='unique')
    op.drop_column('statsheet', 'subclassId')
    op.drop_column('statsheet', 'clazzId')
    op.create_foreign_key(None, 'user_role', 'role', ['roleId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.add_column('statsheet', sa.Column('clazzId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('statsheet', sa.Column('subclassId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('statsheet_subclassId_key', 'statsheet', ['subclassId'])
    op.create_unique_constraint('statsheet_clazzId_key', 'statsheet', ['clazzId'])
    op.drop_constraint(None, 'class_subclasses', type_='foreignkey')
    # ### end Alembic commands ###
